//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food()
        {
            this.component_value = new HashSet<component_value>();
            this.specdiet = new HashSet<specdiet>();
        }
    
        public int FOODID { get; set; }
        public string FOODNAME { get; set; }
        public string FOODTYPE { get; set; }
        public string PROCESS { get; set; }
        public Nullable<int> EDPORT { get; set; }
        public string IGCLASS { get; set; }
        public string IGCLASSP { get; set; }
        public string FUCLASS { get; set; }
        public string FUCLASSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<component_value> component_value { get; set; }
        public virtual foodtype_FI foodtype_FI { get; set; }
        public virtual fuclass_FI fuclass_FI { get; set; }
        public virtual fuclass_FI fuclass_FI1 { get; set; }
        public virtual igclass_FI igclass_FI { get; set; }
        public virtual igclass_FI igclass_FI1 { get; set; }
        public virtual process_FI process_FI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<specdiet> specdiet { get; set; }
    }
}
