//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MittayksikkoLista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MittayksikkoLista()
        {
            this.ReseptienAinesosaLista = new HashSet<ReseptienAinesosaLista>();
        }
    
        public int MittayksikkoID { get; set; }
        public string Mittayksikko { get; set; }
        public string MittayksikkoSelite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReseptienAinesosaLista> ReseptienAinesosaLista { get; set; }
    }
}
