//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseptienAinesosienVaihde
    {
        public int RiviID { get; set; }
        public int ReseptiID { get; set; }
        public int ReseptiAinesosaListaID { get; set; }
    
        public virtual ReseptienAinesosaLista ReseptienAinesosaLista { get; set; }
        public virtual Reseptit Reseptit { get; set; }
    }
}
