//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReseptienAinesosaLista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReseptienAinesosaLista()
        {
            this.ReseptienAinesosienVaihde = new HashSet<ReseptienAinesosienVaihde>();
        }
    
        public int ReseptiAinesosaListaID { get; set; }
        public int RaakaAineID { get; set; }
        public decimal Maara { get; set; }
        public int MittayksikkoID { get; set; }
    
        public virtual MittayksikkoLista MittayksikkoLista { get; set; }
        public virtual RaakaAineet RaakaAineet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReseptienAinesosienVaihde> ReseptienAinesosienVaihde { get; set; }
    }
}
