//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReseptiHakuEntities2 : DbContext
    {
        public ReseptiHakuEntities2()
            : base("name=ReseptiHakuEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<component_value> component_value { get; set; }
        public virtual DbSet<eufdname_FI> eufdname_FI { get; set; }
        public virtual DbSet<food> food { get; set; }
        public virtual DbSet<foodtype_FI> foodtype_FI { get; set; }
        public virtual DbSet<fuclass_FI> fuclass_FI { get; set; }
        public virtual DbSet<igclass_FI> igclass_FI { get; set; }
        public virtual DbSet<Kategoriat> Kategoriat { get; set; }
        public virtual DbSet<MenuLista> MenuLista { get; set; }
        public virtual DbSet<MenunKategoriat> MenunKategoriat { get; set; }
        public virtual DbSet<MenuVaihde> MenuVaihde { get; set; }
        public virtual DbSet<MittayksikkoLista> MittayksikkoLista { get; set; }
        public virtual DbSet<process_FI> process_FI { get; set; }
        public virtual DbSet<RaakaAineet> RaakaAineet { get; set; }
        public virtual DbSet<ReseptienAinesosaLista> ReseptienAinesosaLista { get; set; }
        public virtual DbSet<ReseptienAinesosienVaihde> ReseptienAinesosienVaihde { get; set; }
        public virtual DbSet<ReseptienVaiheet> ReseptienVaiheet { get; set; }
        public virtual DbSet<ReseptienVaiheidenLista> ReseptienVaiheidenLista { get; set; }
        public virtual DbSet<Reseptit> Reseptit { get; set; }
        public virtual DbSet<specdiet> specdiet { get; set; }
        public virtual DbSet<specdiet_FI> specdiet_FI { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user_component_value> user_component_value { get; set; }
        public virtual DbSet<user_eufdname_FI> user_eufdname_FI { get; set; }
        public virtual DbSet<user_food> user_food { get; set; }
        public virtual DbSet<user_foodtype_FI> user_foodtype_FI { get; set; }
        public virtual DbSet<user_fuclass_FI> user_fuclass_FI { get; set; }
        public virtual DbSet<user_igclass_FI> user_igclass_FI { get; set; }
        public virtual DbSet<user_process_FI> user_process_FI { get; set; }
        public virtual DbSet<user_specdiet> user_specdiet { get; set; }
        public virtual DbSet<user_specdiet_FI> user_specdiet_FI { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<SuosikkiLinkit> SuosikkiLinkit { get; set; }
        public virtual DbSet<SuosikkiMenut> SuosikkiMenut { get; set; }
        public virtual DbSet<SuosikkiReseptit> SuosikkiReseptit { get; set; }
    }
}
