//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class specdiet
    {
        public int EDMX_ID { get; set; }
        public int FOODID { get; set; }
        public string SPECDIET1 { get; set; }
    
        public virtual food food { get; set; }
        public virtual specdiet_FI specdiet_FI { get; set; }
    }
}
