//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_component_value
    {
        public int EDMX_ID { get; set; }
        public int FOODID { get; set; }
        public string EUFDNAME { get; set; }
        public string BESTLOC { get; set; }
        public string ACQTYPE { get; set; }
        public string METHTYPE { get; set; }
        public string METHIND { get; set; }
    
        public virtual user_eufdname_FI user_eufdname_FI { get; set; }
        public virtual user_food user_food { get; set; }
    }
}
