//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReseptiHaku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_specdiet
    {
        public int EDMX_ID { get; set; }
        public int FOODID { get; set; }
        public string SPECDIET { get; set; }
    
        public virtual user_food user_food { get; set; }
        public virtual user_specdiet_FI user_specdiet_FI { get; set; }
    }
}
